### ISSUE TITLE
Sur firefox sur téléphone portable les icônes du bas sont inaccessibles

### ISSUE THREAD

**Issue by lhamon53** [Ozytis/albiziapp-react#39]
Sous firefox sur téléphone portable (Androïd, Galaxy S7 edge) les icônes du bas sont inaccessibles car couvertes par la barre d'adresse

**Comment by kevinpoirier** [comment]
Vu avec Sébastien, de ne pas prendre en compte les navigateurs mobiles peu voir pas utilisé. (Firefox et Opera sur mobile qui ont très peu de part de marché)
