### ISSUE TITLE
Sur opéra sur téléphone portable, la carte ne s'affiche pas

### ISSUE THREAD

**Issue by lhamon53** [Ozytis/albiziapp-react#40]
Sous opéra sur téléphone portable (Androïd, Galaxy S7 edge) la carte ne s'affiche pas

**Comment by kevinpoirier** [comment]
Vu avec Sébastien, de ne pas prendre en compte les navigateurs mobiles peu voir pas utilisé. (Firefox et Opera sur mobile qui ont très peu de part de marché)
